### ISSUE TITLE
Suggest new icons and favicon

### ISSUE THREAD

**Issue by NitinNair89** [NitinNair89/TheHungryRecipes#10]
**Enhancement:**
I am looking for a new icon as well as a favicon for this project. Please share your suggestions in the comments below.

**Comment by alanprayoga** [comment]
I suggest you to use line icon for base icon pack for the website, such as [lineicons](https://lineicons.com). And use the chef hat on random recipe button for the favicon.

**Comment by kunalkashyap855** [comment]
You can also use the fontawesome.io library for icons. It has a host of cool icons and is very easy to integrate with html.

**Comment by NitinNair89** [comment]
There are not much icons used in this project. I was looking for a custom design if anyone wants to contribute :slightly_smiling_face:

**Comment by pjawneh** [comment]
Do you have a list of icons needed? I might give it a try...

**Comment by NitinNair89** [comment]
> Do you have a list of icons needed? I might give it a try...

I don't. You can suggest few :)

**Comment by pjawneh** [comment]
> 
> 
> > Do you have a list of icons needed? I might give it a try...
> 
> I don't. You can suggest few :)

Okay, I'll try to work on  a few soon

**Comment by pjawneh** [comment]
**proposed logo**

![logo-test](https://user-images.githubusercontent.com/17254999/67177252-5f87fb00-f393-11e9-89ba-31ee12d1602f.PNG)


**proposed favicon**
![favi](https://user-images.githubusercontent.com/17254999/67177338-c60d1900-f393-11e9-8000-ca04a4f57431.PNG)

**proposed search icon**
![search](https://user-images.githubusercontent.com/17254999/67177352-d3c29e80-f393-11e9-9068-874b8aa08e1c.PNG)


**and working on one for random recipes**

**Comment by NitinNair89** [comment]
> **proposed logo**
> 
> ![logo-test](https://user-images.githubusercontent.com/17254999/67177252-5f87fb00-f393-11e9-89ba-31ee12d1602f.PNG)
> 
> **proposed favicon**
> ![favi](https://user-images.githubusercontent.com/17254999/67177338-c60d1900-f393-11e9-8000-ca04a4f57431.PNG)
> 
> **proposed search icon**
> ![search](https://user-images.githubusercontent.com/17254999/67177352-d3c29e80-f393-11e9-9068-874b8aa08e1c.PNG)
> 
> **and working on one for random recipes**

I liked the main logo. Any different variants for search? Because it will look cluttered when size is reduced.

**Comment by pjawneh** [comment]
Not yet, I’ll try a few more ideas

**Comment by pjawneh** [comment]
> 
> 
> > **proposed logo**
> > ![logo-test](https://user-images.githubusercontent.com/17254999/67177252-5f87fb00-f393-11e9-89ba-31ee12d1602f.PNG)
> > **proposed favicon**
> > ![favi](https://user-images.githubusercontent.com/17254999/67177338-c60d1900-f393-11e9-8000-ca04a4f57431.PNG)
> > **proposed search icon**
> > ![search](https://user-images.githubusercontent.com/17254999/67177352-d3c29e80-f393-11e9-9068-874b8aa08e1c.PNG)
> > **and working on one for random recipes**
> 
> I liked the main logo. Any different variants for search? Because it will look cluttered when size is reduced.

search:
![search](https://user-images.githubusercontent.com/17254999/67542429-6627b280-f6b2-11e9-86b9-b96842706792.PNG)


random recipe:

![recipe](https://user-images.githubusercontent.com/17254999/67542431-6de75700-f6b2-11e9-8d27-46901f501d64.PNG)
