### ISSUE TITLE
List meal categories below the input field for quick search

### ISSUE THREAD

**Issue by NitinNair89** [NitinNair89/TheHungryRecipes#13]
**Enhancement:**
List meal categories to enable users to perform a quick search

---

Currently in development by @saguins #12

**Comment by kushaggarwal** [comment]
i would like to work on it 
Where would you like to have the categories listed upon the page

**Comment by NitinNair89** [comment]
> i would like to work on it
> Where would you like to have the categories listed upon the page

It's already under development. Please see the last line in the issue description :slightly_smiling_face:

**Comment by kushaggarwal** [comment]
Okay Thank you
