### ISSUE TITLE
Fix alignment of the Random Recipe button

### ISSUE THREAD

**Issue by NitinNair89** [NitinNair89/TheHungryRecipes#14]
**What's the bug?**
Currently, the position of the Random Recipe button is a little off and not in alignment with the text beside it.

**Expected behavior**
The Random Recipe button should be aligned with the text beside it. Use the ```d-flex``` class for the row and use flex properties to align the button. Also make sure the icon stays with the button.

---

IF YOU WANT TO WORK ON THIS, PLEASE CLAIM IT BY COMMENTING BELOW.

**Comment by learnerjay** [comment]
I will like to work on it

**Comment by kushaggarwal** [comment]
I would like to work on it

**Comment by NitinNair89** [comment]
> I will like to work on it

Go ahead!

**Comment by learnerjay** [comment]
> I will like to work on it
> 
> Go ahead!

Unable to solve as div % is applied & separately. 
@kushaggarwal . You can work on it.

**Comment by NitinNair89** [comment]
> > I will like to work on it
> > Go ahead!
> 
> Unable to solve as div % is applied & separately.
> @kushaggarwal . You can work on it.

You can show us what you've tried. Are you good with CSS flexbox? It's really simple. :)

@kushaggarwal are you taking this up?

**Comment by Bhaveshm23** [comment]
@NitinNair89  try this
```
.row:first-child{display: flex; align-items: center;}
section#landing .row .chefimg{top:4px; right:-6px;}
section#random .row .chefimg{top:28px;right:-14px}
```

**Comment by Bhaveshm23** [comment]
@NitinNair89 
Fixed the button alignment. Please have a look at it.
