### ISSUE TITLE
Make the site responsive

### ISSUE THREAD

**Issue by NitinNair89** [NitinNair89/TheHungryRecipes#2]
**Enhancement:**
- Currently the website is not responsive and the UI breaks at many places

**What I want:**
- A good approach to making the website responsive and easily accessible to all screen sizes

---

**IF YOU WANT TO WORK ON THIS, PLEASE CLAIM IT BY COMMENTING BELOW**

**Comment by thebhushanmhatre** [comment]
Hi @NitinNair89,
I would like to work on this

**Comment by NitinNair89** [comment]
Go ahead! :slightly_smiling_face:

**Comment by akashsark** [comment]
Hey I would like to work on this

**Comment by NitinNair89** [comment]
> Hey I would like to work on this

Go ahead!

**Comment by NitinNair89** [comment]
> Hey I would like to work on this

Hi @akashsark - Are you working on this? Would love to have your updates.

**Comment by ranjit-ao** [comment]
If this is no longer being worked on, I am willing to help. From what I see, it looks like some headers are overlapping with the text and so on when the window is resized, is this what you would like corrected? No need to assign this to me, but I will attempt to put a pr through in the next few days with some fixes.

**Comment by NitinNair89** [comment]
> If this is no longer being worked on, I am willing to help. From what I see, it looks like some headers are overlapping with the text and so on when the window is resized, is this what you would like corrected? No need to assign this to me, but I will attempt to put a pr through in the next few days with some fixes.

Go ahead

**Comment by michellelim** [comment]
i'd also like to take a stab at this

**Comment by ttolentino89** [comment]
is bootstrap an option? if so I can happily fix this for you :D

**Comment by NitinNair89** [comment]
> is bootstrap an option? if so I can happily fix this for you :D

We're not using Bootstrap. It would be heavy for this small web application. That's why I purposely prefered the Skeleton CSS library for minimal code.

**Comment by NitinNair89** [comment]
> is bootstrap an option? if so I can happily fix this for you :D

Saw your PR and added a comment. Please check once :)

**Comment by SuvamPrasd** [comment]
Can I use Boostrap 4 framework to make the website responsive?

**Comment by SuvamPrasd** [comment]
If bootstrap is not in the option then I will use the skeleton CSS library to make the website responsive over any device.

**Comment by NitinNair89** [comment]
> Can I use Boostrap 4 framework to make the website responsive?

Unfortunately no. Please see the comment thread above :slightly_smiling_face:

**Comment by NitinNair89** [comment]
> If bootstrap is not in the option then I will use the skeleton CSS library to make the website responsive over any device.

Sure. Send PR with breakpoints screenshots or GitHub pages link for your repo so I can test.
