### ISSUE TITLE
latest recipe api endpoint is paid only

### ISSUE THREAD

**Issue by PaulLiamAG** [NitinNair89/TheHungryRecipes#21]
**Describe the bug**

the latest recipe button will not load any data as the api owner has made that endpoint paid only.

you need to support them via patreon in order to get access.

here is the link: https://www.patreon.com/thedatadb

**To Reproduce**
1. Go to the homepage
2. Click on latest
3. Scroll down to latest recipe
4. See error in console or by going to the endpoint in the web browser: https://www.themealdb.com/api/json/v1/1/latest.php

**Expected behavior**
the latest recipe will load.

**Screenshots**
not needed

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 77.0.3865.90

**Smartphone (please complete the following information):**
not tested on a smartphone.

**Additional context**
maybe you can contact them and get access as this is an open source project?

**Comment by NitinNair89** [comment]
Let's remove the latest recipes section. Submit your PR

**Comment by PaulLiamAG** [comment]
That seems like the best option for now.

I will submit a PR to remove the section and related code.

**Comment by NitinNair89** [comment]
> That seems like the best option for now.
> 
> I will submit a PR to remove the section and related code.

Thank you so much. I will be waiting for your PR
