### ISSUE TITLE
no recipe available message 

### ISSUE THREAD

**Issue by PaulLiamAG** [NitinNair89/TheHungryRecipes#25]
**Is your feature request related to a problem? Please describe.**
When you search for a keyword and it does not find any results it just scrolls you down to the last search without telling you it found no recipes. or if you have not searched before it does not do anything whatsoever.  

**Describe the solution you'd like**
I would like to add a message if no recipes are found so the user knows what's going on.
something on the lines of: "Hmm looks like we dont have any recipes for <keyword>, would you like to search again? <search button>"

**Describe alternatives you've considered**
I think showing a helpful message is the only option.

**Additional context**
try to search for "ko", it should take you down to the past search or do nothing if you have not searched before.

**Comment by PaulLiamAG** [comment]
I can submit a PR to take care of this issue if you think it needs fixing.

**Comment by NitinNair89** [comment]
I couldn't reproduce this. I typed "ko*  and clicked the search recipe button. It did nothing. Can you check?

**Comment by PaulLiamAG** [comment]
that's the issue, when the keyword ko or any other keyword that has no recipes is typed.
The user does not get notified that no recipes exist for that keyword.
I would like to add a message when no recipes are returned by the api.

**Comment by NitinNair89** [comment]
> that's the issue, when the keyword ko or any other keyword that has no recipes is typed.
> The user does not get notified that no recipes exist for that keyword.
> I would like to add a message when no recipes are returned by the api.

Oh, got it. Go ahead. Send the PR :+1:

**Comment by PaulLiamAG** [comment]
I'm still working on this, I have the error message part working but I'm running into a bug with auto scroll triggering when the search button is clicked. I will have it fixed soon and create the PR.

**Comment by NitinNair89** [comment]
> I'm still working on this, I have the error message part working but I'm running into a bug with auto scroll triggering when the search button is clicked. I will have it fixed soon and create the PR.

Let's not trigger the auto-scroll. We can scroll the page once we're sure there's data. Until then add a spinner/loader to let users know something is happening. Once we are sure that we have records, we can use offset() to auto-scroll.

What do you think?
