### ISSUE TITLE
clear search code not running on button click

### ISSUE THREAD

**Issue by PaulLiamAG** [NitinNair89/TheHungryRecipes#26]
**Describe the bug**
The code added recently to clear the search box when the user clicks the random button does not seem to run.

**To Reproduce**
1. Go to homepage
2. Search for a recipe
3. Click the random button
4. The search box does not clear.

**Expected behavior**
when you click the random button the search box should be reset to blank.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: chrome
 - Version 77.0.3865.90

**Smartphone (please complete the following information):**
not tested

**Additional context**
I can submit a PR that fixes this issue.

**Comment by NitinNair89** [comment]
Go ahead. Thanks so much for actively contributing :+1:
