### ISSUE TITLE
Fixed sticky Header when scrolling

### ISSUE THREAD

**Issue by RodolfoBrian** [NitinNair89/TheHungryRecipes#35]
1. I suggest you to make a fixed header when scroll. 
`display: block;
 width: 100%;  background: #b2f11d;
z-index: 100; border-top: 1px solid #eee;
border-bottom: 1px solid #eee;
background-color: white;
padding: 45px;
position: fixed;`  will be more attractive for the user. add a `padding:  45px; `for the header. 

2. add a link for the Brand "The Hungry Recipes"  Make remarkable bold and  change the  background color for example : `background-color : #eef2c7;`.

3. For the "Cards  i would suggest to make some modification:  for example 
`.card {
    border-radius: 7px;
    margin: 10px;
    background: rgb(234, 234, 229);
    padding: 10px;
}`

have many more you can do for you site... etc

Reference links : 
 https://codepen.io/JGallardo/pen/lJoyk
https://www.w3schools.com/howto/howto_js_sticky_header.asp

**Comment by RodolfoBrian** [comment]
> 1. I suggest you to make a fixed header when scroll.
>    `display: block;  width: 100%;  background: #b2f11d; z-index: 100; border-top: 1px solid #eee; border-bottom: 1px solid #eee; background-color: white; padding: 45px; position: fixed;`  will be more attractive for the user. add a `padding:  45px; `for the header.
> 2. add a link for the Brand "The Hungry Recipes"  Make remarkable bold and  change the  background color for example : `background-color : #eef2c7;`.
> 3. For the "Cards  i would suggest to make some modification:  for example
>    `.card { border-radius: 7px; margin: 10px; background: rgb(234, 234, 229); padding: 10px; }`
> 
> have many more you can do for you site... etc



> 1. I suggest you to make a fixed header when scroll.
>    `display: block;  width: 100%;  background: #b2f11d; z-index: 100; border-top: 1px solid #eee; border-bottom: 1px solid #eee; background-color: white; padding: 45px; position: fixed;`  will be more attractive for the user. add a `padding:  45px; `for the header.
> 2. add a link for the Brand "The Hungry Recipes"  Make remarkable bold and  change the  background color for example : `background-color : #eef2c7;`.
> 3. For the "Cards  i would suggest to make some modification:  for example
>    `.card { border-radius: 7px; margin: 10px; background: rgb(234, 234, 229); padding: 10px; }`
> 
> have many more you can do for you site... etc

**Comment by NitinNair89** [comment]
Fork this repo, do your changes and share screenshot.

**Comment by RodolfoBrian** [comment]
@NitinNair89 Hi  can you label this issue  with  'Hacktoberfest'

**Comment by NitinNair89** [comment]
> @NitinNair89 Hi can you label this issue with 'Hacktoberfest'

Won't you contribute otherwise? :)

**Comment by RodolfoBrian** [comment]
yes for sure i will

**Comment by RodolfoBrian** [comment]
> > @NitinNair89 Hi can you label this issue with 'Hacktoberfest'
> 
> Won't you contribute otherwise? :)

yes for sure i will

**Comment by RodolfoBrian** [comment]
![thehungryrecipe](https://user-images.githubusercontent.com/9575060/67168278-cf4db400-f39a-11e9-9702-d428cfe4800a.gif)

**Comment by NitinNair89** [comment]
The header color doesn't match with the website theme. Please change. Also remove extra padding. Keep "whitesmoke" as body background color
