### ISSUE TITLE
Update About section

### ISSUE THREAD

**Issue by NitinNair89** [NitinNair89/TheHungryRecipes#37]
**Is your feature request related to a problem? Please describe.**
Currently the about section is quite incomplete.

**Describe the solution you'd like**
Good content about what the web application is and other details/badges (you can get it from readme file). Also update the statement to "Maintained by Nitin" since we have good number of contributions now. :slightly_smiling_face: 

**Additional**
You can come up with your suggestions.

---
IF YOU WANT TO WORK ON IT, PLEASE CLAIM BY COMMENTING BELOW

**Comment by tobifroe** [comment]
I'd like to work on this! :)

**Comment by NitinNair89** [comment]
@Tobsl3r - Are you still working on this?
