### ISSUE TITLE
Create a new "Search Recipe" button

### ISSUE THREAD

**Issue by NitinNair89** [NitinNair89/TheHungryRecipes#4]
**Enhancement:**
- Currently there's no "Search Recipe" button in the above-the-fold content in the page. Most visitors will easily get confused due to the positioning of the "Random Recipe" button beside the input field.
- Clicking this button will trigger the search functionality which is already implemented in the web app

**What I want?**
A new "Search Recipe" button with the same style or different (you can improvise) beside the input field or below the random recipe button vertically stacked.

**Any other ideas?**
You're welcome to share any other ideas for solving this issue

---

**IF YOU WANT TO WORK ON THIS ISSUE, PLEASE CLAIM IT BY COMMENTING BELOW**

**Comment by alexresiga** [comment]
i will start working on this now

**Comment by NitinNair89** [comment]
> i will start working on this now

Go ahead! :+1:

**Comment by NitinNair89** [comment]
Thank you for contributing, @alexresiga :slightly_smiling_face:
