### ISSUE TITLE
Project url redirects to 404 error page

### ISSUE THREAD

**Issue by gauri242** [NitinNair89/TheHungryRecipes#40]
@NitinNair89 
Link provided under GitHub project redirects to 404 error page

1. Go to GitHub
2. Click on provided project link
3. See error

**Expected behavior**
It should load proper web content

 - Windows 10
 - Chrome browser

<img width="958" alt="404 Error" src="https://user-images.githubusercontent.com/56014138/136060525-c4181f5f-5a42-40a6-a990-1b006cf4962f.png">

**Comment by NitinNair89** [comment]
Thanks @gauri242 
Please send a PR with the fix.

**Comment by NitinNair89** [comment]
Fixed by @gauri242. Closing.
