### ISSUE TITLE
Implement cache mechanism

### ISSUE THREAD

**Issue by NitinNair89** [NitinNair89/TheHungryRecipes#6]
**Enhancement:**
Implement cache mechanism to serve the website faster

**Suggestion:**
Use browser's cache to load results faster when refreshing the page. The current code hits the API to fetch results. We can restrict that and load the previously displayed results if user refreshes the page

Any other suggestions welcome! :slightly_smiling_face: 

---

IF YOU WANT TO WORK ON THIS ISSUE, PLEASE CLAIM IT BY COMMENTING BELOW

**Comment by yunior05** [comment]
👋 I can do this

**Comment by NitinNair89** [comment]
>  I can do this

Go ahead. Send your PR once done. Also setup GitHub pages to point your fork so that I can test it
