### ISSUE TITLE
Random recipe button does not work after search

### ISSUE THREAD

**Issue by NitinNair89** [NitinNair89/TheHungryRecipes#7]
**Description:**
After performing a search for any food material, the random recipe button in the first section just scrolls the page and does not fetch a random recipe

**To Reproduce:**
1. Search for any food material (For eg. apple, fish, etc.)
2. Click on the Search Recipe button
3. Page will auto-scroll to search results. Click the "Recipe" button from any card
4. Recipe is displayed, click the "Search again" button to scroll up the page
5. Click the "Random Recipe" button. It will scroll down and show the previous searched recipe instead of a random recipe

**Expected Behavior:**
Once a search is completed, clicking on the random recipe should fetch a random recipe and clear the input field

---

IF YOU WANT TO WORK ON THIS ISSUE, PLEASE CLAIM IT BY COMMENTING BELOW

**Comment by alanprayoga** [comment]
Hi @NitinNair89  👋 I would like to work on this.

**Comment by NitinNair89** [comment]
Go ahead. Also setup your fork repo's GitHub pages to point your fork repo URL

**Comment by NitinNair89** [comment]
Thanks for contributing, @alanpryoga  :slightly_smiling_face:
